### ISSUE TITLE
Missing hist module

### ISSUE THREAD

**Issue by wecassidy** [zctao/omnifoldTop#12]
[histogramming.py](python/histogramming.py) imports a `hist` module that isn't checked in to version control. The issue was introduced in d8c8e2e in util.py (see [the diff](https://github.com/zctao/omnifoldTop/commit/d8c8e2e058b56371cc1ff67d6528aef64bcd5e47#diff-6a7ef7dc1545fbe9e571a1315dd52d6da9327e737bb07a74826fb13ff0ed1ed6R10)).

**Comment by zctao** [comment]
The `hist` module (https://github.com/scikit-hep/hist) needs to be installed via pip.
We'll have to update the requirement.txt at some point.
